using System.Text;

namespace StudySummarizer.Services;

public class StubSummarizer : ISummarizer
{
    public Task<string> SummarizeAsync(string text, string length, string? focus)
    {
        var sentenceCount = length.ToLowerInvariant() switch
        {
            "short" => 2,
            "long" => 6,
            _ => 3
        };

        var sentences = text
            .Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Take(sentenceCount);

        var sb = new StringBuilder();
        sb.AppendLine("[SUMMARY GENERATED BY STUB — not real AI]");
        if (!string.IsNullOrWhiteSpace(focus))
            sb.AppendLine($"Requested focus: {focus}");
        sb.AppendLine();
        foreach (var s in sentences)
            sb.AppendLine($"• {s}.");

        return Task.FromResult(sb.ToString());
    }
}
